/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hack_jni_NdkJniUtils */

#ifndef _Included_com_android_hack_jni_NdkJniUtils
#define _Included_com_android_hack_jni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_hack_jni_NdkJniUtils
 * Method:    getUserName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_hack_jni_NdkJniUtils_getUserName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
