/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_hack_jni_NdkJniUtils */

#ifndef _Included_com_android_hack_jni_NdkJniUtils
#define _Included_com_android_hack_jni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_hack_jni_NdkJniUtils
 * Method:    getContent
 * Signature: ()Ljava/lang/String;
 */
/*
 * const修饰常量, 定义时初始化
 * const char *content与char * const content的区别:
 * 前者表示指针可以指向不同的数据, 但它们指向的数据自身不能被修改
 * 后者表示指针本身的值不能被修改, 不能指向不同的数据
 */
const char *content;
// char * const content;

typedef struct {
    jint age;
    jboolean gender;
    const char *name;
    jfloat weight;
} UserInfo;

UserInfo jUserInfo;

JNIEXPORT jstring JNICALL Java_com_android_hack_jni_NdkJniUtils_getContent
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_android_hack_jni_NdkJniUtils_setContent
        (JNIEnv *, jobject, jstring content);

JNIEXPORT jobject JNICALL Java_com_android_hack_jni_NdkJniUtils_getUserInfo
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_android_hack_jni_NdkJniUtils_setUserInfo
        (JNIEnv *, jobject, jobject userInfo);

#ifdef __cplusplus
}
#endif
#endif
